services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - .:/app
    ports:
      - ${PHP_BIND_PORT}:9000
    env_file:
      - .env
  webserver:
    image: nginx:latest
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
